export const en = {
  auth: {
    emailLabel: 'Email',
    errors: {
      emailTaken: 'An account already exists for that email address.',
      failedLogin:
        'The app could not sign you in with that email and password.',
      failedRegistration: 'The app could not create your account.',
      usernameTaken: 'That username is already in use.',
    },
    guestHint: 'Sign in is required before any shopping data is available.',
    loadingSignIn: 'Signing in...',
    loadingSignUp: 'Creating account...',
    nextStep:
      'Authentication screens and form handling will connect to this guest shell in the next task.',
    passwordLabel: 'Password',
    primaryAction: 'Sign in coming next',
    signInAction: 'Sign in',
    signInTitle: 'Sign in',
    signUpAction: 'Create account',
    signUpTitle: 'Create account',
    subtitle:
      'Private shopping lists stay behind the auth gate. Session bootstrap is already wired through Supabase.',
    switchToSignIn: 'Already have an account? Sign in',
    switchToSignUp: 'Need an account? Create one',
    title: 'Welcome back',
    usernameLabel: 'Username',
  },
  common: {
    actions: {
      cancel: 'Cancel',
      confirm: 'Confirm',
      delete: 'Delete',
      save: 'Save',
    },
    errors: {
      deleteFailed: 'The app could not delete the requested data.',
      loadFailed: 'The app could not load data from Supabase.',
      network: 'A network or server error interrupted the request.',
      saveFailed: 'The app could not save your changes.',
      sessionLoad:
        'The app could not restore the current session from Supabase.',
      supabaseEnvMissing:
        'Supabase environment variables are missing. Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_ANON_KEY to a local .env file.',
    },
    feedback: {
      changesSaved: 'Changes saved.',
      itemAdded: 'Item added.',
      itemDeleted: 'Item deleted.',
      itemUpdated: 'Item updated.',
      listCreated: 'List created.',
      listDeleted: 'List deleted.',
      listRenamed: 'List renamed.',
    },
  },
  items: {
    addAction: 'Add item',
    completedLabel: 'Completed',
    creating: 'Adding item...',
    defaultQuantityHint: 'Quantity defaults to 1 when left blank.',
    deleteAction: 'Delete item',
    editAction: 'Edit item',
    emptyDescription:
      'Add your first item to start tracking shopping progress.',
    emptyTitle: 'No items yet',
    loading: 'Loading items in this list...',
    markCompletedAction: 'Mark complete',
    markPendingAction: 'Mark pending',
    nameLabel: 'Item name',
    namePlaceholder: 'Milk',
    pendingLabel: 'Pending',
    quantityLabel: 'Quantity',
    quantityPlaceholder: '1',
    quantityValue: 'Quantity: {{count}}',
    updating: 'Saving item...',
  },
  navigation: {
    listDetailTitle: 'List details',
    signInTitle: 'Sign in',
    signUpTitle: 'Create account',
    shoppingListsHomeTitle: 'Shopping lists',
  },
  shell: {
    loadingSession: 'Checking your local Supabase session...',
  },
  shoppingLists: {
    confirmDeleteMessage:
      'Delete "{{name}}"? All items in this list will be removed as well.',
    confirmDeleteTitle: 'Delete this shopping list?',
    createAction: 'Create list',
    creating: 'Creating list...',
    deleting: 'Deleting list...',
    namePlaceholder: 'Groceries for Saturday',
    createTitle: 'New shopping list',
    deleteAction: 'Delete list',
    emptyDescription:
      'Create a list to keep your next shopping trip organized.',
    emptyTitle: 'No shopping lists yet',
    loadFailedTitle: 'Shopping lists are unavailable',
    loading: 'Loading your shopping lists...',
    noEmail: 'Signed-in email unavailable',
    openAction: 'Open list',
    progressLabel: 'Progress',
    progressValue: '{{completed}}/{{total}} completed',
    renamePlaceholder: 'Updated shopping list name',
    renameAction: 'Rename list',
    renameTitle: 'Rename list',
    renaming: 'Saving name...',
    signOutAction: 'Sign out',
    subtitle:
      'Authenticated navigation, providers, and session restore are ready for feature implementation.',
    title: 'Shopping list shell',
    updatedLabel: 'Updated {{date}}',
  },
  validation: {
    invalidEmail: 'Enter a valid email address.',
    invalidQuantity: 'Enter a quantity greater than 0.',
    requiredItemName: 'Item name is required.',
    requiredListName: 'List name is required.',
    requiredUsername: 'Username is required.',
    shortPassword: 'Password must be at least 6 characters long.',
  },
} as const;
